# Generated by Django 4.2.5 on 2025-06-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('code_barre', models.BigIntegerField()),
                ('qte', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('periode', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='etablissement_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type', models.IntegerField()),
                ('domaine', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('art', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='etablissement_client_simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='etablissement_fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type', models.IntegerField()),
                ('domaine', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('art', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fam', models.CharField(max_length=100)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='gestiondata.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='FamilleCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codif', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilleClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codif', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilleFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codif', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilleProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codif', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonArtIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonArtOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonEntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonSortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonTransfertIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonTransfertOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('nbrcolis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('code_barre', models.CharField(max_length=13)),
                ('famille', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('TVA', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('qte', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_Menu', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_url', models.CharField(max_length=100)),
                ('four_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='gestiondata.etablissement_client')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.etablissement_client')),
            ],
        ),
        migrations.CreateModel(
            name='StockMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('idart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('idart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Sfamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sfam', models.CharField(max_length=100)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.famille')),
            ],
        ),
        migrations.CreateModel(
            name='RecetteProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('prix_revient', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('qteresultat', models.IntegerField(default=0)),
                ('idart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles')),
                ('idmatierepremier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('id_Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles')),
                ('id_Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='gestiondata.url'),
        ),
        migrations.AddField(
            model_name='menu',
            name='articles',
            field=models.ManyToManyField(through='gestiondata.Menu_Article', to='gestiondata.articles'),
        ),
        migrations.AddField(
            model_name='menu',
            name='type_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.typemenu'),
        ),
        migrations.CreateModel(
            name='List_Client_ClientSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.ManyToManyField(to='gestiondata.etablissement_client')),
                ('id_client_simple', models.ManyToManyField(to='gestiondata.etablissement_client_simple')),
            ],
        ),
        migrations.CreateModel(
            name='Fr_Dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domain', models.CharField(default='Unknown', max_length=100)),
                ('id_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.domain')),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.etablissement_client')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.etablissement_client'),
        ),
        migrations.CreateModel(
            name='code_barre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_barre', to='gestiondata.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='gestiondata.categorie'),
        ),
    ]
