# Generated by Django 4.2.5 on 2025-06-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonArtIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonArtOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonEntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonLiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonSortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('propreot', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('numeros', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.devis'),
        ),
        migrations.AlterField(
            model_name='lignebonartin',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebonartout',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='ligneboncmd',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebonentreestock',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebonliv',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebonsortiestock',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebontransfertin',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignebontransfertout',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles'),
        ),
        migrations.CreateModel(
            name='ArticleChargesProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('prix_revient', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('qteresultat', models.IntegerField(default=0)),
                ('idart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles')),
                ('idcharges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.charges')),
            ],
        ),
        migrations.AddField(
            model_name='lignebonartin',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_art_in', to='gestiondata.bonartin'),
        ),
        migrations.AddField(
            model_name='lignebonartout',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_art_out', to='gestiondata.bonartout'),
        ),
        migrations.AddField(
            model_name='ligneboncmd',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_cmd', to='gestiondata.boncmd'),
        ),
        migrations.AddField(
            model_name='lignebonentreestock',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_entree_stock', to='gestiondata.bonentreestock'),
        ),
        migrations.AddField(
            model_name='lignebonliv',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_liv', to='gestiondata.bonliv'),
        ),
        migrations.AddField(
            model_name='lignebonsortiestock',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_sortie_stock', to='gestiondata.bonsortiestock'),
        ),
        migrations.AddField(
            model_name='lignebontransfertin',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_transfert_in', to='gestiondata.bontransfertin'),
        ),
        migrations.AddField(
            model_name='lignebontransfertout',
            name='idbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ligne_bon_transfert_out', to='gestiondata.bontransfertout'),
        ),
    ]
