# Generated by Django 5.1.7 on 2025-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('site', models.URLField(default='https://codeitdz.com')),
            ],
        ),
    ]
