# Generated by Django 5.1.7 on 2025-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_redirection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirection',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
